### ISSUE TITLE
Can't get license to work

### ISSUE THREAD

**Issue by exitrip** [seb1992/aras-innovator-docker#1]
We are having  no success with a new license from ARAS for 12SP9. 

We have triple checked the MAC addresses and XML syntax, rebuilt the docker images multiple times.  

The docker-compose builds and runs fine, but all the demo logins result in "License Key is Invalid"

Here's an example of different formats we've tried in the XML file (not all at once):
```
<!-- name=REDATCED mac_address=REDATCED version=12.0 -->
<License company="" act_key="REDATCED " lic_key="Redacted" lic_type="Unlimited"/>

<License act_key="REDATCED " lic_key="Redacted" lic_type="Unlimited" company=""/>

<License  lic_type="Unlimited"  lic_key="Redacted" act_key="REDATCED " />
```

Any pointers or guidance to get the login working would be of great help.  Does this not work with the Free license?

**Comment by seb1992** [comment]
Hi, I just retried rebuilding the image with a free license from Aras and it worked, so that should not be a problem. 

In my XML file it looks like this:
`<!-- name=Individuals - Germany   mac_address=xx-xx-xx-xx-xx-xx   version=12.0  -->`
`<License  lic_type="Unlimited" lic_key="xxx" act_key="xxx"/>`

The first thing I would try for troubleshooting is to copy the InnovatorServerConfig (or inspect the files in the container with a Visual Studio extension or something) out of the container to check if your InnovatorServerConfig was copied there correctly and contains your license key. You can copy the InnovatorServerConfig.xml out of the container (after stopping it) with the following command:
`docker cp arasinnovator:C:\Innovator\innovatorserverconfig.xml C:\temp\checkinnovatorserverconfig.xml`

Replace the "C:\temp\checkinnovatorserverconfig.xml" with any other path on your local machine if needed.

**Comment by exitrip** [comment]
Thank you for the response, I should've added that we are on a Windows host using Docker Desktop.  It looks like that might `mac_address` not be supported?  Are you on linux?

**Comment by exitrip** [comment]
I see now that this compose file is for a Windows Host, and we've gotten past the `License Key is Invalid` error, and now get `Authentication failed for innovator` (and every other user we try).  I think we can figure out the username password stuff.

**Comment by seb1992** [comment]
@exitrip 

username: admin
password: innovator

That should work. Seems  I forgot that in the README, I am going to add that tomorrow morning.

**Comment by exitrip** [comment]
Danke!
